name: E2E on Chrome
on:
  workflow_dispatch:
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        job: [0, 1, 3 ]
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
        with:
          command: npm run cy:run:cloud
          browser: chrome
